addSbtPlugin("org.scala-js" % "sbt-scalajs" % "1.22.0")
addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.6.2")
addSbtPlugin("ch.epfl.scala" % "sbt-scalafix" % "0.14.9")
addSbtPlugin("org.wartremover" % "sbt-wartremover" % "3.6.2")
addSbtPlugin("org.wartremover" % "sbt-wartremover-contrib" % "2.4.5")
